### ISSUE TITLE
How can I Pass two value in spinner one for ID and second for Title

### ISSUE THREAD

**Issue by mukesh-makavana** [MdFarhanRaja/SearchableSpinner#12]
Hello Md Farhan,

I want to create app using your spinner in this app i want to show item title but i want to get two value id and title (item name) when i click on spinner item.

so please tell me how can i set custom ID and Title With Array List and get access it on click event.

**Comment by devsarfo** [comment]
Hi, I think I have a better solution for you
Declare two variables:
ArrayList<String> ids;
ArrayList<String> labels;

And then the object variable list 
List<Supplier> suppliers;

for (Supplier supplier : suppliers) {
           ids.add(supplier.getId().toString());
            labels.add(supplier.getCompanyName());
}

spdItems.bindOnSpinerListener(new OnSpinerItemClick() {
            @Override
            public void onClick(String item, int position) {
                //TO get id use the position
                String id = ids.get(position);
                String label = lables.get(position);
            }
        });

hope this works
