### ISSUE TITLE
How to change Text and Dialog box color in your library

### ISSUE THREAD

**Issue by MakavanaMukesh** [MdFarhanRaja/SearchableSpinner#14]
Hello, 
Please Tell me How can i change Text color of Item and also Dialogbox because it is very important for suitable Application. 

Please Reply Me As soon as possible.

Thanks,
Mukesh

**Comment by MdFarhanRaja** [comment]
For this i have to publish new version then you will able to change colors.

**Comment by 1AhsanSyed** [comment]
have you update this color issue ?

**Comment by arifhakkim** [comment]
https://github.com/MdFarhanRaja/SearchableSpinner/issues/29#issuecomment-512155561

This issue has been fixed with version 2.1
