### ISSUE TITLE
Shows Error

### ISSUE THREAD

**Issue by AkshayKawale** [MdFarhanRaja/SearchableSpinner#15]
java.lang.NoSuchFieldError: No field close of type I in class Lin/galaxyofandroid/spinerdialog/R$id; or its superclasses (declaration of 'in.galaxyofandroid.spinerdialog.R$id' appears in package)

**Comment by MdFarhanRaja** [comment]
i used this library in latest android studio 3.1 & there is no error. 

Can you tell me which version of studio u r using & when u r getting this error.
