### ISSUE TITLE
ID issue

### ISSUE THREAD

**Issue by PRIYADHARSHINI9** [MdFarhanRaja/SearchableSpinner#17]
When i use same item name with two different id. onclicking the items it returns the same id 
eg. when i use item name as item1 with id1 
and item1 with id2 

on clicking it returns same id as id1

itemName
item1 as Aj with id 7
item2 as Aj with id 9
but on clicking it returns same id as 7

![ddd](https://user-images.githubusercontent.com/28855726/42085890-471d7a7a-7baf-11e8-8a83-0e0ad4051b90.png)
![gggg](https://user-images.githubusercontent.com/28855726/42085891-476393e8-7baf-11e8-8392-1f5b5290c1e5.png)

**Comment by MdFarhanRaja** [comment]
You have to pass unique items

**Comment by PRIYADHARSHINI9** [comment]
Thank you for your response sir.
