### ISSUE TITLE
Diable Animation or change animation

### ISSUE THREAD

**Issue by vartakpratik** [MdFarhanRaja/SearchableSpinner#2]
I didnt found any method or way to disable slide up to enter animation or change.

Can you please guide mi for the same

**Comment by MdFarhanRaja** [comment]
currently i'm working on that. Once it completed i will inform you.

**Comment by vartakpratik** [comment]
Thank you for reply.
I am looking forward for the same.

**Comment by MdFarhanRaja** [comment]
Hi vartakpratik,
Now you can change or disable animation. Kindly follow instructions on README.MD.
Thanks....
