### ISSUE TITLE
wrong posotion getting the searchble spinner

### ISSUE THREAD

**Issue by cviacmob** [MdFarhanRaja/SearchableSpinner#21]
Am using searchable spinner but i have a duplicate data but getting the position has worngly

**Comment by MdFarhanRaja** [comment]
Kindly Remove duplicate data from list

**Comment by cviacmob** [comment]
no sir one data based on the another spinner

**Comment by cviacmob** [comment]
![4290131759427841096](https://user-images.githubusercontent.com/23516580/51741973-657bd480-20be-11e9-85d2-2c18ac0766d5.jpg)

this is the screenshot sir

**Comment by cviacmob** [comment]
kindly help me

**Comment by MdFarhanRaja** [comment]
why both number is same. it should be unique number then you are able to search perfectly

**Comment by MdFarhanRaja** [comment]
i dont understand what you exactly want/need

**Comment by cviacmob** [comment]
thankq for response sir, have working
