### ISSUE TITLE
Handle Back Pressed 

### ISSUE THREAD

**Issue by gasscoelho** [MdFarhanRaja/SearchableSpinner#27]
Hi,

I was trying to handle the "back pressed" to close the dialog but since i'm working inside a fragment i'm not able to get the back's event.  

So to avoid close the dialog only in the "closeTitle" (_rippleViewClose_) i'm setting a true value for "cancellable" through _setCancellable()_. But I think would be a nice feature be able to handle these back's events.

btw, congrats for the project.

**Comment by gasscoelho** [comment]
I didn't notice that setCancellable() works fine when press back button. 

Sorry. xD

**Comment by MdFarhanRaja** [comment]
No issue. You are welcome.
