### ISSUE TITLE
color

### ISSUE THREAD

**Issue by pallavbansal** [MdFarhanRaja/SearchableSpinner#29]
spinner dialog text color is white so there is nothing visible please help me out
here is my id - pallavbansal2@gmail.com

**Comment by MdFarhanRaja** [comment]
Can you please send me screenshot

**Comment by pallavbansal** [comment]
sure here it is 
![Screenshot_2019-07-10-22-30-16-050_com example ca](https://user-images.githubusercontent.com/36406421/60989105-b0369380-a362-11e9-8e16-e3e23e6c60e3.png)

**Comment by MdFarhanRaja** [comment]
Thanks for sharing the screenshot.
I will publish one new version tomorrow with fix this issue.

And i will inform you once done

**Comment by pallavbansal** [comment]
okk thanks.

**Comment by pallavbansal** [comment]
sir did you solve it ?

**Comment by MdFarhanRaja** [comment]
Working on it... Just about to finish

**Comment by pallavbansal** [comment]
sir would you please provide me the method for changing the color of background of spinner , i just need that for my project i can't delay it anymore.

**Comment by MdFarhanRaja** [comment]
Just wait 30 minutes

**Comment by MdFarhanRaja** [comment]
Issue Solved... Update the library to 2.1 and use following methods for changing the colors

        spinnerDialog.setTitleColor(getResources().getColor(R.color.colorAccent));
        spinnerDialog.setSearchIconColor(getResources().getColor(R.color.colorAccent));
        spinnerDialog.setSearchTextColor(getResources().getColor(R.color.colorAccent));
        spinnerDialog.setItemColor(getResources().getColor(R.color.colorAccent));
        spinnerDialog.setItemDividerColor(getResources().getColor(R.color.colorAccent));
        spinnerDialog.setCloseColor(getResources().getColor(R.color.colorAccent));

**Comment by MdFarhanRaja** [comment]
Issue Solved... Update the library to 2.1 and use following methods for
changing the colors

    spinnerDialog.setTitleColor(getResources().getColor(R.color.colorAccent));
    spinnerDialog.setSearchIconColor(getResources().getColor(R.color.colorAccent));
    spinnerDialog.setSearchTextColor(getResources().getColor(R.color.colorAccent));
    spinnerDialog.setItemColor(getResources().getColor(R.color.colorAccent));
    spinnerDialog.setItemDividerColor(getResources().getColor(R.color.colorAccent));
    spinnerDialog.setCloseColor(getResources().getColor(R.color.colorAccent));

**Comment by pallavbansal** [comment]
thanks sir

**Comment by pallavbansal** [comment]
sir how can i use this spinner in fragment ?

**Comment by pallavbansal** [comment]
on context it gives error,help me out please.

**Comment by eskeikim** [comment]
use getActivity()
