### ISSUE TITLE
Cannot compile into Android Studio 3.0 Canary 4

### ISSUE THREAD

**Issue by carmas123** [MdFarhanRaja/SearchableSpinner#3]
Cannot compile into Android Studio 3.0 Canary 4.
I got an error when use it in AS 3.0 Canary 4:

style attribute @android:attr/windowEnterAnimation not found
style attribute @android:attr/windowExitAnimation not found

Please remove the "@" prefix from style.xml

        <item name="android:windowEnterAnimation">@anim/slide_in_bottom</item>
        <item name="android:windowExitAnimation">@anim/slide_out_top</item>

**Comment by MdFarhanRaja** [comment]
I think it's an Android Studio 3.0 Bug. Once Studio(3.0) will Stable then i will fix it.
