### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by viratsoft** [MdFarhanRaja/SearchableSpinner#35]
ERROR: Could not find com.github.MdFarhanRaja:SearchableSpinner:2.0.
Searched in the following locations:
  - https://jcenter.bintray.com/com/github/MdFarhanRaja/SearchableSpinner/2.0/SearchableSpinner-2.0.pom
  - https://jcenter.bintray.com/com/github/MdFarhanRaja/SearchableSpinner/2.0/SearchableSpinner-2.0.jar
  - https://maven.google.com/com/github/MdFarhanRaja/SearchableSpinner/2.0/SearchableSpinner-2.0.pom
  - https://maven.google.com/com/github/MdFarhanRaja/SearchableSpinner/2.0/SearchableSpinner-2.0.jar
  - https://dl.google.com/dl/android/maven2/com/github/MdFarhanRaja/SearchableSpinner/2.0/SearchableSpinner-2.0.pom
  - https://dl.google.com/dl/android/maven2/com/github/MdFarhanRaja/SearchableSpinner/2.0/SearchableSpinner-2.0.jar
Required by:
Project

**Comment by MdFarhanRaja** [comment]
Kindly add this to your project level gradle

allprojects {
	repositories {
		maven { url 'https://jitpack.io' }
	}
}

**Comment by vihatsoft** [comment]
after change url to jitpack.io then get error: 
ERROR: Failed to resolve: androidx.appcompat:appcompat:1.1.0
Add Google Maven repository and sync project
---
my old repositories : 
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
