### ISSUE TITLE
I get the problem when I wear android studio 3.0

### ISSUE THREAD

**Issue by ghost** [MdFarhanRaja/SearchableSpinner#7]
I get the problem when I wear android studio 3.0, exactly when I enter
<style name = "DialogAnimations" />
<style name = "DialogAnimations.SmileWindow">
    <item name = "@ android: windowEnterAnimation"> @ anim / slide_in_bottom </ item>
    <item name = "@ android: windowExitAnimation"> @ anim / slide_out_top </ item>
</ style>
it looks like the latest version of android studio no longer support this .. I am waiting for your latest version that can be used in android studio 3.0 .. thanks

**Comment by MdFarhanRaja** [comment]
Kindly use latest version 1.7

**Comment by MdFarhanRaja** [comment]
Kindly use latest version 1.7
